### ISSUE TITLE
Memory clean after generate

### ISSUE THREAD

**Issue by mykeehu** [mattyamonaca/PBRemTools#3]
In cascadePSP I set the memory value too high and got a CUDA error. After that, I couldn't generate anything because the model was stuck in video memory and kept taking up video memory.
Is it possible to add a function that automatically removes the model from memory after generating? Option or button is fine, but then I wouldn't have to restart the whole webui.

**Comment by ANTONIOPSD** [comment]
same problem here, OOM every time

**Comment by feixiaomi** [comment]
same problem

**Comment by mykeehu** [comment]
Again, there are memory errors, like the one I just got. 
How to reopen the Issue?

```
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\main.py", line 32, in processing
    mask, image = get_foreground(image, td_abg_enabled, h_split, v_split, n_cluster, alpha, th_rate, cascadePSP_enabled, fast, psp_L, sa_enabled, seg_query, model_name, predicted_iou_threshold, stability_score_threshold, clip_threshold)
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\td_abg.py", line 138, in get_foreground
    mask = get_sa_mask(img, query, model_name, predicted_iou_threshold, stability_score_threshold, clip_threshold)
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\sa_mask.py", line 160, in get_sa_mask
    masks = segment(predicted_iou_threshold, stability_score_threshold, clip_threshold, image, query, model_name)
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\sa_mask.py", line 145, in segment
    masks = filter_masks(
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\sa_mask.py", line 112, in filter_masks
    scores = get_scores(cropped_masks, query)
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\sa_mask.py", line 72, in get_scores
    model, preprocess = load_clip()
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\sa_mask.py", line 54, in load_clip
    model, preprocess = clip.load(name, device=device)
AttributeError: module 'clip' has no attribute 'load'
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\main.py", line 32, in processing
    mask, image = get_foreground(image, td_abg_enabled, h_split, v_split, n_cluster, alpha, th_rate, cascadePSP_enabled, fast, psp_L, sa_enabled, seg_query, model_name, predicted_iou_threshold, stability_score_threshold, clip_threshold)
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\td_abg.py", line 96, in get_foreground
    mask = get_sa_mask(img, query, model_name, predicted_iou_threshold, stability_score_threshold, clip_threshold)
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\sa_mask.py", line 160, in get_sa_mask
    masks = segment(predicted_iou_threshold, stability_score_threshold, clip_threshold, image, query, model_name)
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\sa_mask.py", line 145, in segment
    masks = filter_masks(
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\sa_mask.py", line 112, in filter_masks
    scores = get_scores(cropped_masks, query)
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\sa_mask.py", line 72, in get_scores
    model, preprocess = load_clip()
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\sa_mask.py", line 54, in load_clip
    model, preprocess = clip.load(name, device=device)
AttributeError: module 'clip' has no attribute 'load'
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\main.py", line 32, in processing
    mask, image = get_foreground(image, td_abg_enabled, h_split, v_split, n_cluster, alpha, th_rate, cascadePSP_enabled, fast, psp_L, sa_enabled, seg_query, model_name, predicted_iou_threshold, stability_score_threshold, clip_threshold)
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\td_abg.py", line 106, in get_foreground
    mask = get_sa_mask(img, query, model_name, predicted_iou_threshold, stability_score_threshold, clip_threshold)
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\sa_mask.py", line 160, in get_sa_mask
    masks = segment(predicted_iou_threshold, stability_score_threshold, clip_threshold, image, query, model_name)
  File "H:\Stable-Diffusion-Automatic\automatic\extensions\PBRemTools\scripts\sa_mask.py", line 144, in segment
    masks = mask_generator.generate(image)
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\segment_anything\automatic_mask_generator.py", line 163, in generate
    mask_data = self._generate_masks(image)
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\segment_anything\automatic_mask_generator.py", line 206, in _generate_masks
    crop_data = self._process_crop(image, crop_box, layer_idx, orig_size)
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\segment_anything\automatic_mask_generator.py", line 236, in _process_crop
    self.predictor.set_image(cropped_im)
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\segment_anything\predictor.py", line 60, in set_image
    self.set_torch_image(input_image_torch, image.shape[:2])
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\segment_anything\predictor.py", line 89, in set_torch_image
    self.features = self.model.image_encoder(input_image)
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\segment_anything\modeling\image_encoder.py", line 112, in forward
    x = blk(x)
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\segment_anything\modeling\image_encoder.py", line 174, in forward
    x = self.attn(x)
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\automatic\venv\lib\site-packages\segment_anything\modeling\image_encoder.py", line 231, in forward
    attn = (q * self.scale) @ k.transpose(-2, -1)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 12.00 GiB total capacity; 9.56 GiB already allocated; 0 bytes free; 10.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
