### ISSUE TITLE
ERROR message - Can not use the extension

### ISSUE THREAD

**Issue by Shangooriginal** [mattyamonaca/PBRemTools#4]
Added the extension and my first attempt to use it. I keep getting the below message. Is there something I'm doing wrong?

Traceback (most recent call last):
  File "C:\Users\XXXX\Documents\WebUI-Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\XXXX\Documents\WebUI-Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Users\XXXX\Documents\WebUI-Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\XXXX\Documents\WebUI-Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\XXXX\Documents\WebUI-Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\XXXX\Documents\WebUI-Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
TypeError: processing() takes 10 positional arguments but 12 were given

**Comment by mattyamonaca** [comment]
Sorry, With the next update, this program is currently experiencing a bug. Please wait as we will address it as soon as possible.

**Comment by 2blackbar** [comment]
I dont recommend installing this extension , its processing image for ages, you have to really wait a long time for it to process the image and load requirements, its not worth it, just use regular bgremoval extension until this gets resolved

**Comment by mattyamonaca** [comment]
Resolved by latest update. If the problem persists, please resume.
