### ISSUE TITLE
not working!

### ISSUE THREAD

**Issue by xxl2005** [mattyamonaca/PBRemTools#41]
hello problem not working! manjaro linux

`Error running install.py for extension /home/tobias/stable-diffusion-webui/extensions/PBRemTools.
Command: "/home/tobias/stable-diffusion-webui/venv/bin/python3" "/home/tobias/stable-diffusion-webui/extensions/PBRemTools/install.py"
Error code: 1
stdout: Installing onnxruntime for PBRemTools

stderr: Traceback (most recent call last):
  File "/home/tobias/stable-diffusion-webui/extensions/PBRemTools/install.py", line 16, in <module>
    launch.run_pip(f'install {target}', desc=f'{name} for PBRemTools')
  File "/home/tobias/stable-diffusion-webui/modules/launch_utils.py", line 124, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobias/stable-diffusion-webui/modules/launch_utils.py", line 101, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install onnxruntime for PBRemTools.
Command: "/home/tobias/stable-diffusion-webui/venv/bin/python3" -m pip install onnxruntime-gpu==1.14.0 --prefer-binary
Error code: 1
stderr: ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.14.0 (from versions: 1.15.0)
ERROR: No matching distribution found for onnxruntime-gpu==1.14.0
Error loading script: api.py
Traceback (most recent call last):
  File "/home/tobias/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobias/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/tobias/stable-diffusion-webui/extensions/PBRemTools/scripts/api.py", line 9, in <module>
    from scripts.main import process_image, model_list
  File "/home/tobias/stable-diffusion-webui/extensions/PBRemTools/scripts/main.py", line 15, in <module>
    from scripts.td_abg import get_foreground
  File "/home/tobias/stable-diffusion-webui/extensions/PBRemTools/scripts/td_abg.py", line 5, in <module>
    from sklearn.cluster import KMeans, MiniBatchKMeans
ModuleNotFoundError: No module named 'sklearn'

Error loading script: main.py
Traceback (most recent call last):
  File "/home/tobias/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobias/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/tobias/stable-diffusion-webui/extensions/PBRemTools/scripts/main.py", line 15, in <module>
    from scripts.td_abg import get_foreground
  File "/home/tobias/stable-diffusion-webui/extensions/PBRemTools/scripts/td_abg.py", line 5, in <module>
    from sklearn.cluster import KMeans, MiniBatchKMeans
ModuleNotFoundError: No module named 'sklearn'

Error loading script: sa_mask.py
Traceback (most recent call last):
  File "/home/tobias/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobias/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/tobias/stable-diffusion-webui/extensions/PBRemTools/scripts/sa_mask.py", line 13, in <module>
    from segment_anything import SamAutomaticMaskGenerator, sam_model_registry
ModuleNotFoundError: No module named 'segment_anything'

Error loading script: td_abg.py
Traceback (most recent call last):
  File "/home/tobias/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobias/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/tobias/stable-diffusion-webui/extensions/PBRemTools/scripts/td_abg.py", line 5, in <module>
    from sklearn.cluster import KMeans, MiniBatchKMeans
ModuleNotFoundError: No module named 'sklearn'`

**Comment by chace20** [comment]
```
ModuleNotFoundError: No module named 'sklearn'
```

Are you install `sklearn`?
