### ISSUE TITLE
Error when using SAM_CLIP

### ISSUE THREAD

**Issue by tsound97** [mattyamonaca/PBRemTools#5]
Traceback (most recent call last):
  File "A:\v1.5\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "A:\v1.5\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "A:\v1.5\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "A:\v1.5\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "A:\v1.5\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "A:\v1.5\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "A:\v1.5\stable-diffusion-webui\extensions\PBRemTools\scripts\main.py", line 19, in processing
    mask, image = get_foreground(image, td_abg_enabled, h_split, v_split, n_cluster, alpha, th_rate, cascadePSP_enabled, fast, psp_L, sa_enabled, seg_query)
  File "A:\v1.5\stable-diffusion-webui\extensions\PBRemTools\scripts\td_abg.py", line 131, in get_foreground
    mask = get_sa_mask(img, query)
  File "A:\v1.5\stable-diffusion-webui\extensions\PBRemTools\scripts\sa_mask.py", line 147, in get_sa_mask
    masks = segment(predicted_iou_threshold, stability_score_threshold, clip_threshold, image, query)
  File "A:\v1.5\stable-diffusion-webui\extensions\PBRemTools\scripts\sa_mask.py", line 126, in segment
    mask_generator = load_mask_generator()
  File "A:\v1.5\stable-diffusion-webui\extensions\PBRemTools\scripts\sa_mask.py", line 29, in load_mask_generator
    sam = sam_model_registry[MODEL_TYPE](checkpoint=CHECKPOINT_PATH).to(device)
  File "A:\v1.5\stable-diffusion-webui\venv\lib\site-packages\segment_anything\build_sam.py", line 15, in build_sam_vit_h
    return _build_sam(
  File "A:\v1.5\stable-diffusion-webui\venv\lib\site-packages\segment_anything\build_sam.py", line 105, in _build_sam
    state_dict = torch.load(f)
  File "A:\v1.5\stable-diffusion-webui\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "A:\v1.5\stable-diffusion-webui\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "A:\v1.5\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "A:\v1.5\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

**Comment by mattyamonaca** [comment]
Resolved by latest update. If the problem persists, please resume.
