### ISSUE TITLE
HELP!!! Module Not FoundError: No module named 'modules.paths_internal'

### ISSUE THREAD

**Issue by AIwebUI** [mattyamonaca/PBRemTools#7]
Closing server running on port: 7860
Restarting UI...
Error loading script: main.py
Traceback (most recent call last):
  File "*****\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "*****\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "*****\extensions\PBRemTools\scripts\main.py", line 12, in <module>
    from scripts.td_abg import get_foreground
  File "*****\extensions\PBRemTools\scripts\td_abg.py", line 30, in <module>
    from scripts.sa_mask import  get_sa_mask
  File "*****\extensions\PBRemTools\scripts\sa_mask.py", line 17, in <module>
    from modules.paths_internal import extensions_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

Error loading script: sa_mask.py
Traceback (most recent call last):
  File "*****\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "*****\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "*****\extensions\PBRemTools\scripts\sa_mask.py", line 17, in <module>
    from modules.paths_internal import extensions_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

Error loading script: td_abg.py
Traceback (most recent call last):
  File "*****\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "*****\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "*****\extensions\PBRemTools\scripts\td_abg.py", line 30, in <module>
    from scripts.sa_mask import  get_sa_mask
  File "*****\extensions\PBRemTools\scripts\sa_mask.py", line 17, in <module>
    from modules.paths_internal import extensions_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

**Comment by NoCrypt** [comment]
Fixed in #8
